### ISSUE TITLE
linking in via the URL isn't quite working 

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/ZZBrowse#22]
I was going to point Steven to an example of a cowpea QTL on Vu05 that matched some soybean GWAS on Gm18, but this link:
http://dev.lis.ncgr.org:50003/shiny/ZBrowse/?tab=Chrom&datasets=Cowpea%20QTL&chr=Vu05&selected=907871&window=250000&datasets2=Soybean%20GWAS&chr2=Gm18&selected2=57035000&window2=250000&traits=Days%20to%20flowering;Flower%20color;Flowering%20time%20under%20long%20daylength%20at%20UCR-CES;Flowering%20time%20under%20short%20daylength%20at%20CVARS&genomicLinkage=true&neighbors=40&matched=20&intermediate=5&selectedGene=vigun.Vigun05g010900&relatedRegion=Gm18%2056.75-57.32%20Mbp

seems to take me to Vu01 instead. 

per Sven:

> Confirmed, though the problem is not specific to QTL data. This should be a separate issue, I suspect it has to do with > the need to reset the chromosome view when the user changes an organism. (Except in this case where we do it 
> programmatically through the URL.)

I'll note additionally that soybean does go to the right chromosome when the link is traversed. not sure if that is significant to figuring out the resolution...

**Comment by svengato** [comment]
"This redistribution of chromosome views is trickier than I thought!"

As a workaround, Steven can select Vu05 after clicking that link and ending up at Vu01.

**Comment by adf-ncgr** [comment]
> "This redistribution of chromosome views is trickier than I thought!"

"He links to lupine 5, but lands on cowpea 1... Son of a gun!"

I should also note that the selection of traits recorded in the URL isn't being respected when the link is followed.

**Comment by svengato** [comment]
Try it now - I am still working on edge cases, but your example should succeed.

**Comment by adf-ncgr** [comment]
Yes, works as expected now- thanks! 
@cann0010 try : http://dev.lis.ncgr.org:50003/shiny/ZBrowse/?tab=Chrom&datasets=Cowpea%20QTL&chr=Vu05&selected=907871&window=250000&datasets2=Soybean%20GWAS&chr2=Gm18&selected2=57035000&window2=250000&traits=Days%20to%20flowering;Flower%20color;Flowering%20time%20under%20long%20daylength%20at%20UCR-CES;Flowering%20time%20under%20short%20daylength%20at%20CVARS&traits2=Days%20to%20flower;First%20flower;Flower%20color&genomicLinkage=true&neighbors=40&matched=20&intermediate=5&selectedGene=vigun.Vigun05g010900&relatedRegion=Gm18%2056.75-57.32%20Mbp
for the cowpea flowering time QTL -> soybean GWAS use case I showed in the meeting earlier in the week

**Comment by svengato** [comment]
> @cann0010 try : http://dev.lis.ncgr.org:50003/shiny/ZBrowse/[...]

Will that get to Steven? It looks like I am the only one cc'd on the message.

**Comment by adf-ncgr** [comment]
I think so, but the ways of github can be mysterious to mortal man(ager)

**Comment by cann0010** [comment]
@svengato @adf-ncgr - got it. 
I see cowpea QTL & soybean GWAS. Cool! That's a nice treat for the end of the week.
Will explore more rigorously in the coming few days.
